apps/reports/api/urls.py
from django.urls import path, include
from apps.reports.api.views import welcome

app_name = 'reports'

urlpatterns = [
    ## REST DJANGO API
    path('', welcome, name="reports_api"),
]

apps/reports/urls.py
from django.urls import path, include
from .views import dashboard, index, Companies, AddDevices, Devices

app_name = 'reports'

urlpatterns = [
    path('', index, name="index"),
    path('dashboard', dashboard, name='dashboard'),
    path('companies', Companies.as_view(), name='companies'),
    path('devices', Devices.as_view(), name='devices'),
    path('devices/edit_devices/<str:action>/<str:id>',
         Devices.as_view(), name="edit_device"),
    path('companies/edit_companies/<str:action>/<str:id>', Companies.as_view(), name="edit_company"),
    path('companies/add', Companies.as_view(), name="add_company"),
    path('devices/add', AddDevices.as_view(), name='add_device'),
]

iotSense/urls.py
from django.contrib import admin
from apps.reports.views import index, dashboard
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.reports.urls', namespace='reports')),
    path('api/', include('apps.reports.api.urls', namespace='rest_framework')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
]

apps/reports/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Company(models.Model):
    company_name = models.CharField(max_length=200)
    company_id = models.CharField(max_length=200, default="0000")
    company_location = models.CharField(max_length=200)

    def __str__(self):
        return self.company_name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    position = models.CharField(max_length=200, default='None')

    def __str__(self):
        return self.user.username


class SensorType(models.Model):
    variable_name = models.CharField(max_length=300)
    variable_description = models.CharField(max_length=1000)

    def __str__(self):
        return self.variable_name

class Device(models.Model):
    device_name = models.CharField(max_length=200)
    device_mac = models.CharField(max_length=200)
    device_id = models.CharField(max_length=200, default="0000")
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    sensor_type = models.ForeignKey(SensorType, on_delete=models.CASCADE, default='')
    
    def __str__(self):
        title = '%s | %s' %(self.device_id, self.device_name)
        return title

class DeviceInfo(models.Model):
    temperature = models.CharField(max_length=200, default='', blank=True, null=True)
    humidity = models.CharField(max_length=200, default='', blank=True, null=True)
    state = models.CharField(max_length=200, default='', blank=True, null=True)
    timestamp = models.DateTimeField(default=timezone.now)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

apps/reports/forms.py
from django.forms import ModelForm
from .models import Device


class AddDeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = '__all__'

apps/reports/api/views.py
from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .common import DataDecodification
import datetime

@api_view(["GET", "POST"])
def welcome(request):
    if request.method == 'POST':
        data = request.data
        decoded_data = DataDecodification(data).data_decode()
        if decoded_data != None:
            decoded_data.save()        
            return Response(data)
        else: 
            return Response(status=200)
    else:
        content = {"message": "Welcome to the BookStore!"}
        return JsonResponse(content)

apps/reports/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.shortcuts import render, get_object_or_404, redirect
from .models import Device, Profile, Company, DeviceInfo
from .forms import AddDeviceForm
from django.utils import timezone


def index(request):
    return render(request, 'reports/index.html')

# @method_decorator(login_required) Used on class based views
@login_required
def dashboard(request):
    user = request.user
    devices, devices_info = validation_superuser(user)
    try:
        devices_info = devices_info.order_by('-timestamp')
        online_devices, offline_devices = active_devices(devices)
        data = {
            'devices': devices,
            'devices_info': devices_info,
            'online': online_devices,
            'offline': offline_devices
        }
    except:
        data = {
            'devices': devices,
            'devices_info': devices_info,
            'online': 0,
            'offline': 0
        }

    return render(request, 'reports/dashboard.html', data)


@method_decorator(login_required, name='get')
# @method_decorator(user_passes_test(lambda u: u.is_superuser), name='get')
class Companies(TemplateView):
    template_name = "reports/companies.html"

    def get(self, request):
        try:
            company_data = {}
            companies_objects = Company.objects.all()
            for company in companies_objects:
                number_devices = Device.objects.filter(
                    company=company).count()
                company_data[company.company_name] = [company, number_devices]
            return render(request, self.template_name, {'company_data': company_data})
        except:
            return HttpResponse('<h1> You don\'t have permission to access this page </h1>', status=400)

    def post(self, request, action, id):
        delete(Company, action, id)
        return redirect('reports:companies')

@method_decorator(login_required, name='get')
class Devices(TemplateView):
    template_name = 'reports/devices.html'

    def get(self, request):
        devices_dict = {}
        user = request.user
        devices, _ = validation_superuser(user)
        try:
            for device in devices:
                device_info = DeviceInfo.objects.filter(
                    device=device).order_by('-timestamp')
                devices_dict[device.device_name] = [device, device_info]
        except:
            devices_dict = {}
        return render(request, self.template_name, {'devices_dict': devices_dict})

    def post(self, request, action, id):
        delete(Device, action, id)
        return redirect('reports:devices')

@method_decorator(login_required, name="get")
@method_decorator(user_passes_test(lambda u: u.is_superuser), name='get')
class AddDevices(TemplateView):
    template_name = "reports/add_device.html"

    def get(self, request):
        user = request.user
        if user.is_superuser:
            form = AddDeviceForm()
            return render(request, self.template_name, {'form': form})
        else:
            raise 404

    def post(self, request):
        data = request.POST
        form_filled = AddDeviceForm(data)
        if form_filled.is_valid():
            form_filled.save()
            return redirect("reports:devices")

def validation_superuser(user):
    if user.is_superuser:
        devices = Device.objects.all()
        devices_info = DeviceInfo.objects.all()
    else:
        devices_info = []
        profile = Profile.objects.get(user=user)
        devices = Device.objects.filter(company=profile.company)
        for device in devices:
            devices_info.append(DeviceInfo.objects.filter(device=device))
    return devices, devices_info

def delete(model, action, id):
    if action == 'delete':
        item = get_object_or_404(model, pk=int(id))
        item.delete()

def active_devices(devices):
    online_devices = 0
    offline_devices = 0
    for device in devices:
        last_device_info = DeviceInfo.objects.filter(device=device).last()
        if last_device_info != None:
            time_difference = timezone.now() - last_device_info.timestamp
            seconds_in_day = 24 * 60 * 60
            time_difference = divmod(
                time_difference.days * seconds_in_day + time_difference.seconds, 60)
            if time_difference[0] < 10:
                online_devices += 1
            else:
                offline_devices += 1
    return online_devices, offline_devices

apps/reports/templates/reports/add_device.html
{% extends 'base.html' %}
{% load static %}
{% block title %}AddDevice{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        {% if user.is_authenticated %}
        <form role="form" action="{% url 'reports:add_device' %}" method="POST">
            {% csrf_token %}
            {% for field in form.visible_fields %}
            <div class="form-group form-add-device">
                <label for="">{{ field.label_tag }}</label>
                <div>
                    {{field}}
                </div>
            </div>
            {% endfor %}
            <div class="text-center">
                <button class="btn btn-primary" type="submit">Add device</button>
            </div>
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}

apps/reports/templates/reports/companies.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Companies{% endblock %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"> <a href="{% url 'reports:dashboard' %}">Home</a></li>
    <li class="breadcrumb-item breadcrumb-item-active" ">Companies</a></li>
  </ol>
</nav>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    {% for company, data in company_data.items %}
    <div class="col-md-5 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-header">
          <h6>{{ company }}</h6>
        </div>
        <div class="card-body">
          <div class="container">
            <div class="row">
              <a href="{% url 'reports:devices' %}">Devices: {{ data.1 }} </a>
            </div>
            <div class="row justify-content-center">
              <a href="" class="btn btn-view col-3" method="POST"><i class="fas fa-angle-double-right"></i>View</a>
              <a href="" class="btn btn-edit col-3"><i class="fas fa-edit"></i>Edit</a>
              <form action="{% url 'reports:edit_company' action='delete' id=data.0.id %}" method="POST">
                {%csrf_token%}
                <button type="submit" class="btn btn-delete"><i class="fas fa-trash col-3"></i> Delete</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
{% if user.is_superuser %}
<a href="{% url 'reports:add_company'%}" class="btn-float">
  <i class="fa fa-plus btn-float-wrapper m-10"></i>
</a>
{% endif %}
{% endblock %}

apps/reports/templates/reports/dashboard.html
{% extends 'base.html'%}
{% block title %}Dashboard{% endblock %}
{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item breadcrumb-item-active">Home</a></li>
  </ol>
</nav>
{% endblock %}
{% block content %}
<div class="container-fluid justify-content-center">
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12 p-1">
      <div class="card" id="card-online">
        <div class="card-body">
          <div class="container">
            <div class="row">
              <h3>Online devices: {{ online }} </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-sm-6 col-xs-12 p-1">
      <div class="card" id="card-offline">
        <div class="card-body">
          <div class="container">
            <div class="row">
              <h3>Offline devices: {{ offline }} </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 sm-12 p-1">
      <div class="card" id="card-total">
        <div class="card-body">
          <div class="container">
            <div class="row">
              <h3>Total devices: {{devices.count}} </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <table class="table table-responsive table-hover col-sm-12 col-md-11">
      <thead class="thead">
        <tr>
          <th scope="col">Device id</th>
          <th scope="col">Device name</th>
          <th scope="col">Company</th>
          <th scope="col">Time</th>
          <th scope="col">State</th>
          <th scope="col">Temperature</th>
          <th scope="col">Humidity</th>
        </tr>
      </thead>
      <tbody>
        {% if user.is_superuser %}
          {% for data in devices_info %}
          <tr>
            <th scope="row">{{data.device.device_id}}</th>
            <td>{{data.device.device_name}}</td>
            <td>{{data.device.company}}</td>
            <td>{{data.timestamp}}</td>
            <td>{{data.state}}</td>
            <td>{{data.temperature}}</td>
            <td>{{data.humidity}}</td>
          </tr>
          {% endfor %}
        {% else %}
          {% if devices_info %}
            {% for queryset in devices_info%}
              {% for data in queryset %}
              <tr>
                <th scope="row">{{data.device.device_id}}</th>
                <td>{{data.device.device_name}}</td>
                <td>{{data.device.company}}</td>
                <td>{{data.timestamp}}</td>
                <td>{{data.state}}</td>
                <td>{{data.temperature}}</td>
                <td>{{data.humidity}}</td>
              </tr>
              {% endfor %}
            {% endfor%}
          {% else %}
              <tr>
                <th scope="row">No data to display, please add devices</th>
                </tr>
          {% endif %}
        {% endif %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="container-fluid">
</div>
{% endblock %}

apps/reports/templates/reports/devices.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Companies{% endblock %}


{% block breadcrumb %}
<nav aria-label="nav">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"> <a href="{% url 'reports:dashboard' %}">Home</a></li>
    <li class="breadcrumb-item breadcrumb-item-active">Devices</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        {% if devices_dict %}
            {% for device, data in devices_dict.items %}
            <div class="col-md-5 col-sm-6 col-xs-12">
                <div class="card">
                    <div class="card-header">
                        <b>{{data.0.device_id}}</b>  {{device}}
                    </div>
                    <div class="card-body">
                        <div class="container">
                            <div class="row">
                                <div class="info">
                                    Last comunication:
                                    {% if data.1.0.timestamp %}
                                    {{data.1.0.timestamp}}
                                    {% else %}
                                    {{'No last comunication'}}
                                    {% endif %}
                                </div>
                            </div>
                            <br>
                            <div class="row justify-content-md-center">
                                <button type="button" class="btn btn-view"><i class="fas fa-angle-double-right"></i>
                                    View</button>
                                {% if user.is_authenticated %}
                                <button type="button" class="btn btn-edit"><i class="fas fa-edit"></i> Edit</button>
                                <form action="{% url 'reports:edit_device' action='delete' id=data.0.id %}" method="POST">
                                    {%csrf_token%}
                                    <button type="submit" class="btn btn-delete"><i class="fas fa-trash"></i>
                                        Delete</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="col-md-12">
                <h1>No devices to show. Please, ask the administrator to add devices</h1>
            </div>
        {% endif%}
    </div>
</div>
{% if user.is_superuser %}
<a href="{% url 'reports:add_device'%}" class="btn-float">
    <i class="fa fa-plus btn-float-wrapper m-10"></i>
</a>
{% endif %}
</div>
{% endblock %}

apps/reports/templates/reports/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome | Iot Sense</title>
    <!---Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />
    <!---Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'reports/styles/index.css' %}" />
</head>

<body>
    <section class="home-section-1">
        <div class="container">
            <div class="row">
                <div class="col col-sm-12 col-md-7 mb-4" >
                    <h1> IoT Sense</h1>
                    <p>Developed by Extreme Technologies, Ing. José Lemus</p>
                    <hr>
                    <div class="cta-wrapper">
                        <a href="{% url 'reports:dashboard' %}" class="btn fancy-btn">Get started</a>
                    </div>
                </div>
                <div class="col col-sm-12 col-md-5 mt-4">
                        <img src="{% static 'reports/src/Principal.png' %}" width="354,75" height="354,75" alt="">
                </div>
            </div>
            <div class="row">
                <!-- <div class="btn-group">
                    <a href="https://github.com/jllemus/DjangoApp" type="button" class="btn"><i
                            class="fab fa-github-alt"></i></a>
                    <button type="button" class="btn"><i class="fab fa-google"></i></button>
                    <button type="button" class="btn"><i class="fab fa-facebook"></i></button>
                </div> -->
            </div>
        </div>
    </section>
    
    <footer id="sticky-footer" class="py-2 bg-dark text-white-50">
        <div class="container text-center">
          <small>Copyright &copy;<a class="text-white" href="https://www.linkedin.com/in/jose-luis-lemus-florez-a34943164"> Ing. José Lemus</a></small>
        </div>
    </footer>
</body>

</html>