apps/accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="user_login"),
    path('logout/', LogoutView.as_view(), name='user_logout'),
]

apps/reports/api/urls.py
from django.urls import path, include
from apps.reports.api.views import welcome

app_name = 'reports'

urlpatterns = [
    ## REST DJANGO API
    path('', welcome, name="reports_api"),
]

apps/reports/urls.py
from django.urls import path, include
from .views import dashboard, index, Companies, AddDevices, Devices

app_name = 'reports'

urlpatterns = [
    path('', index, name="index"),
    path('dashboard', dashboard, name='dashboard'),
    path('companies', Companies.as_view(), name='companies'),
    path('devices', Devices.as_view(), name='devices'),
    path('devices/edit_devices/<str:action>/<str:id>',
         Devices.as_view(), name="edit_device"),
    path('companies/edit_companies/<str:action>/<str:id>', Companies.as_view(), name="edit_company"),
    path('companies/add', Companies.as_view(), name="add_company"),
    path('devices/add', AddDevices.as_view(), name='add_device'),
]

iotSense/urls.py
from django.contrib import admin
from apps.reports.views import index, dashboard
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.reports.urls', namespace='reports')),
    path('api/', include('apps.reports.api.urls', namespace='rest_framework')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
]

apps/reports/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Company(models.Model):
    company_name = models.CharField(max_length=200)
    company_id = models.CharField(max_length=200, default="0000")
    company_location = models.CharField(max_length=200)

    def __str__(self):
        return self.company_name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    position = models.CharField(max_length=200, default='None')

    def __str__(self):
        return self.user.username


class SensorType(models.Model):
    variable_name = models.CharField(max_length=300)
    variable_description = models.CharField(max_length=1000)

    def __str__(self):
        return self.variable_name

class Device(models.Model):
    device_name = models.CharField(max_length=200)
    device_mac = models.CharField(max_length=200)
    device_id = models.CharField(max_length=200, default="0000")
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    sensor_type = models.ForeignKey(SensorType, on_delete=models.CASCADE, default='')
    
    def __str__(self):
        title = '%s | %s' %(self.device_id, self.device_name)
        return title

class DeviceInfo(models.Model):
    temperature = models.CharField(max_length=200, default='', blank=True, null=True)
    humidity = models.CharField(max_length=200, default='', blank=True, null=True)
    state = models.CharField(max_length=200, default='', blank=True, null=True)
    timestamp = models.DateTimeField(default=timezone.now)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

apps/reports/forms.py
from django.forms import ModelForm
from .models import Device


class AddDeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = '__all__'

apps/reports/api/views.py
from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .common import DataDecodification
import datetime

@api_view(["GET", "POST"])
def welcome(request):
    if request.method == 'POST':
        data = request.data
        decoded_data = DataDecodification(data).data_decode()
        if decoded_data != None:
            decoded_data.save()        
            return Response(data)
        else: 
            return Response(status=200)
    else:
        content = {"message": "Welcome to the BookStore!"}
        return JsonResponse(content)

apps/reports/views.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.shortcuts import render, get_object_or_404, redirect
from .models import Device, Profile, Company, DeviceInfo
from .forms import AddDeviceForm
from django.utils import timezone


def index(request):
    return render(request, 'reports/index.html')

# @method_decorator(login_required) Used on class based views
@login_required
def dashboard(request):
    user = request.user
    devices, devices_info = validation_superuser(user)
    try:
        devices_info = devices_info.order_by('-timestamp')
        online_devices, offline_devices = active_devices(devices)
        data = {
            'devices': devices,
            'devices_info': devices_info,
            'online': online_devices,
            'offline': offline_devices
        }
    except:
        data = {
            'devices': devices,
            'devices_info': devices_info,
            'online': 0,
            'offline': 0
        }

    return render(request, 'reports/dashboard.html', data)


@method_decorator(login_required, name='get')
# @method_decorator(user_passes_test(lambda u: u.is_superuser), name='get')
class Companies(TemplateView):
    template_name = "reports/companies.html"

    def get(self, request):
        try:
            company_data = {}
            companies_objects = Company.objects.all()
            for company in companies_objects:
                number_devices = Device.objects.filter(
                    company=company).count()
                company_data[company.company_name] = [company, number_devices]
            return render(request, self.template_name, {'company_data': company_data})
        except:
            return HttpResponse('<h1> You don\'t have permission to access this page </h1>', status=400)

    def post(self, request, action, id):
        delete(Company, action, id)
        return redirect('reports:companies')

@method_decorator(login_required, name='get')
class Devices(TemplateView):
    template_name = 'reports/devices.html'

    def get(self, request):
        devices_dict = {}
        user = request.user
        devices, _ = validation_superuser(user)
        try:
            for device in devices:
                device_info = DeviceInfo.objects.filter(
                    device=device).order_by('-timestamp')
                devices_dict[device.device_name] = [device, device_info]
        except:
            devices_dict = {}
        return render(request, self.template_name, {'devices_dict': devices_dict})

    def post(self, request, action, id):
        delete(Device, action, id)
        return redirect('reports:devices')

@method_decorator(login_required, name="get")
@method_decorator(user_passes_test(lambda u: u.is_superuser), name='get')
class AddDevices(TemplateView):
    template_name = "reports/add_device.html"

    def get(self, request):
        user = request.user
        if user.is_superuser:
            form = AddDeviceForm()
            return render(request, self.template_name, {'form': form})
        else:
            raise 404

    def post(self, request):
        data = request.POST
        form_filled = AddDeviceForm(data)
        if form_filled.is_valid():
            form_filled.save()
            return redirect("reports:devices")

def validation_superuser(user):
    if user.is_superuser:
        devices = Device.objects.all()
        devices_info = DeviceInfo.objects.all()
    else:
        devices_info = []
        profile = Profile.objects.get(user=user)
        devices = Device.objects.filter(company=profile.company)
        for device in devices:
            devices_info.append(DeviceInfo.objects.filter(device=device))
    return devices, devices_info

def delete(model, action, id):
    if action == 'delete':
        item = get_object_or_404(model, pk=int(id))
        item.delete()

def active_devices(devices):
    online_devices = 0
    offline_devices = 0
    for device in devices:
        last_device_info = DeviceInfo.objects.filter(device=device).last()
        if last_device_info != None:
            time_difference = timezone.now() - last_device_info.timestamp
            seconds_in_day = 24 * 60 * 60
            time_difference = divmod(
                time_difference.days * seconds_in_day + time_difference.seconds, 60)
            if time_difference[0] < 10:
                online_devices += 1
            else:
                offline_devices += 1
    return online_devices, offline_devices

apps/reports/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'reports/src/icon.png' %}">
    <!---Roboto Font google fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
    <!---Fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous" />

    <!--JQUERY-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!---Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %} | IoT Sense</title>
    <link rel="stylesheet" href="{% static 'reports/styles/style.css' %}" />
</head>

<body>
    <div class="sidebar">
        <div class="sidebar-nav">
            <a class="navbar-brand" href="{% url 'reports:dashboard' %}" id="navbar-title">
                <img src="{% static 'reports/src/logo.png' %}" width="45,5" height="37,5"
                    class="d-inline-block align-top" alt="" loading="lazy">
                IoT Sense
            </a>
        </div>
        <hr>
        {% if user.is_authenticated and user.is_superuser %}
        <div class="sidebar-list">
            <ul>
                <li>
                    <a href="{% url 'reports:companies' %}"><i class="fas fa-city"></i> Companies</a>
                </li>
                <li>
                    <a href="{% url 'reports:devices' %}"><i class="fas fa-server"></i> Devices</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-chart-bar"></i> Reports</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-info-circle"></i> Account</a>
                </li>
                <li>
                    <a href="{% url 'accounts:user_logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </li>
            </ul>
        </div>
        {% else %}
        <div class="sidebar-list">
            <ul>
                <li>
                    <a href="{% url 'reports:devices' %}"><i class="fas fa-server"></i> Devices</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-chart-bar"></i> Reports</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-info-circle"></i> Account</a>
                </li>
                <li>
                    <a href="{% url 'accounts:user_logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </li>
            </ul>
        </div>
        {% endif %}
        <div class="btn-wrapper text-center">
            <div class="btn-group">
                <a href="https://github.com/jllemus/DjangoApp" type="button" class="btn btn-general"><i
                        class="fab fa-github-alt"></i></a>
                <button type="button" class="btn btn-general"><i class="fab fa-google"></i></button>
                <button type="button" class="btn btn-general"><i class="fab fa-facebook"></i></button>
            </div>
        </div>
    </div>
    <div class="content">
        {% block breadcrumb %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
</body>

</html>